name: CI Pipeline

on:
  push:
    branches: [ "main" ] 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      # Build and push Flask API Docker image
      - name: Build the Flask API Docker image
        # run: docker build -t bpetselis01/flask-api -f flask-api/Dockerfile . # This is the original command
        run: docker build -t bpetselis01/flask-api -f flask-api/Dockerfile flask-api

      - name: Push to DockerHub
        run: docker push bpetselis01/flask-api:latest

      # Build and push NextJS Docker image
      - name: Build the NextJS Docker image
        run: docker build -t bpetselis01/nextjs -f frontend/Dockerfile .

      - name: Push to DockerHub
        run: docker push bpetselis01/nextjs:latest