services:
  nextjs:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/cabana:/cabana

  flask-api:
    build: ./flask-api
    ports:
      - "5000:5000"
    volumes:
      - ./flask-api:/flask-api
    env_file: 
      - path: ./.env
    environment:
      - FLASK_APP=index.py

